Repository palantir/palantir-r-sdk, pull requests merged in 2022-04, with the labels that each got.

#1 Add Github Actions
  .github/workflows/build.yaml
Labels: no changelog

#2 Update README.md
  README.md
Labels: no changelog

#3 Make upload_file response invisible
  R/datasets.R
Labels: no changelog

#5 Use r-reticulate environment by default
  .Rbuildignore
  R/install.R
  changelog/@unreleased/pr-5.v2.yml
  man/install_palantir.Rd
Labels: merge when ready

#4 Upgrade to python sdk version 0.5.0
  R/install.R
  man/install_palantir.Rd
Labels: no changelog, autorelease

#7 Upgrade python sdk version to 0.8.0
  R/install.R
  README.md
  man/install_palantir.Rd
Labels: no changelog
